<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $now = Carbon::now();

        // 1. SEED USERS
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Administrator Sistem',
                'email' => 'admin@cahayaonix.com',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'phone' => '081234567890',
                'ikm_name' => 'UD Cahaya Onix & UD Putra Abadi',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'name' => 'Pak Joko Santoso',
                'email' => 'owner@cahayaonix.com',
                'password' => Hash::make('owner123'),
                'role' => 'owner',
                'phone' => '081234567891',
                'ikm_name' => 'UD Cahaya Onix',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'name' => 'Pak Slamet Riyadi',
                'email' => 'gudang@cahayaonix.com',
                'password' => Hash::make('gudang123'),
                'role' => 'gudang',
                'phone' => '081234567892',
                'ikm_name' => 'UD Cahaya Onix',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'name' => 'Mas Budi Prasetyo',
                'email' => 'produksi@cahayaonix.com',
                'password' => Hash::make('produksi123'),
                'role' => 'produksi',
                'phone' => '081234567893',
                'ikm_name' => 'UD Cahaya Onix',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 5,
                'name' => 'Pak Agus Widodo',
                'email' => 'distribusi@cahayaonix.com',
                'password' => Hash::make('distribusi123'),
                'role' => 'distribusi',
                'phone' => '081234567894',
                'ikm_name' => 'UD Cahaya Onix',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // 2. SEED SUPPLIERS
        DB::table('suppliers')->insert([
            [
                'id' => 1,
                'supplier_code' => 'SUP-BSL-01',
                'name' => 'Tambang Marmer Besole Jaya',
                'contact_person' => 'H. Mansur',
                'phone' => '085233112233',
                'address' => 'Desa Besole, Kec. Besuki, Kab. Tulungagung',
                'quarry_location' => 'Tambang Gunung Besole',
                'material_category' => 'Bongkahan Marmer Putih / Krem',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'supplier_code' => 'SUP-CPD-02',
                'name' => 'Penambang Onyx Campurdarat',
                'contact_person' => 'Pak Sumardi',
                'phone' => '081399887766',
                'address' => 'Desa Campurdarat, Kec. Campurdarat, Kab. Tulungagung',
                'quarry_location' => 'Gunung Popoh / Campurdarat',
                'material_category' => 'Bongkahan Onyx Tembus Cahaya',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'supplier_code' => 'SUP-KLS-03',
                'name' => 'Pemasok Batu Kali Song',
                'contact_person' => 'Cak Nardi',
                'phone' => '085744556677',
                'address' => 'Bantaran Kali Song, Kec. Boyolangu, Kab. Tulungagung',
                'quarry_location' => 'Aliran Sungai Kali Song',
                'material_category' => 'Batu Kali Bulat & Pipih',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // 3. SEED CATEGORIES
        DB::table('categories')->insert([
            ['id' => 1, 'name' => 'Bongkahan Batuan Alam', 'slug' => 'bongkahan-batuan-alam', 'type' => 'material', 'description' => 'Bahan baku mentah dari tambang', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 2, 'name' => 'Bahan Kimia & Penolong', 'slug' => 'bahan-kimia-penolong', 'type' => 'material', 'description' => 'Resin, katalis, amplas, kain poles', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 3, 'name' => 'Wastafel Marmer & Onyx', 'slug' => 'wastafel-marmer-onyx', 'type' => 'product', 'description' => 'Produk wastafel sanitari bubut', 'created_at' => $now, 'updated_at' => $now],
            ['id' => 4, 'name' => 'Ornamen Taman & Stepping Stone', 'slug' => 'stepping-stone-taman', 'type' => 'product', 'description' => 'Produk eksterior & pijakan taman', 'created_at' => $now, 'updated_at' => $now],
        ]);

        // 4. SEED MATERIALS
        DB::table('materials')->insert([
            [
                'id' => 1,
                'supplier_id' => 1,
                'material_code' => 'MAT-MRM-001',
                'name' => 'Bongkahan Marmer Putih Campurdarat',
                'type' => 'marmer',
                'grade' => 'grade_a_super',
                'dimension_info' => '80 x 60 x 60 cm',
                'unit' => 'blok',
                'current_stock' => 18.00,
                'minimum_stock' => 5.00,
                'unit_cost' => 450000.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'supplier_id' => 2,
                'material_code' => 'MAT-ONX-001',
                'name' => 'Bongkahan Onyx Kuning Kristal',
                'type' => 'onix',
                'grade' => 'grade_a_super',
                'dimension_info' => '60 x 45 x 45 cm',
                'unit' => 'blok',
                'current_stock' => 12.00,
                'minimum_stock' => 15.00,
                'unit_cost' => 850000.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'supplier_id' => 3,
                'material_code' => 'MAT-BKL-001',
                'name' => 'Batu Kali Alam Kali Song',
                'type' => 'batu_kali',
                'grade' => 'grade_b_standard',
                'dimension_info' => 'Dia 35 - 50 cm',
                'unit' => 'blok',
                'current_stock' => 35.00,
                'minimum_stock' => 10.00,
                'unit_cost' => 95000.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'supplier_id' => null,
                'material_code' => 'MAT-RSN-001',
                'name' => 'Resin Bening Penambal Serat',
                'type' => 'bahan_penolong',
                'grade' => 'grade_a_super',
                'dimension_info' => 'Jerigen 5 Kg',
                'unit' => 'kg',
                'current_stock' => 25.00,
                'minimum_stock' => 10.00,
                'unit_cost' => 65000.00,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // 5. SEED PRODUCTS
        DB::table('products')->insert([
            [
                'id' => 1,
                'category_id' => 3,
                'product_code' => 'PRD-WSM-001',
                'name' => 'Wastafel Marmer Putih D40cm Glossy',
                'material_type' => 'marmer',
                'dimension_spec' => 'Diameter 40cm, Tinggi 15cm',
                'finishing_type' => 'Hi-Glossy Polish',
                'ready_stock' => 24,
                'safety_stock' => 10,
                'standard_cogs' => 175000.00,
                'selling_price' => 385000.00,
                'image_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'category_id' => 3,
                'product_code' => 'PRD-WSO-002',
                'name' => 'Wastafel Oval Onyx Natural Glow D45cm',
                'material_type' => 'onix',
                'dimension_spec' => 'Panjang 45cm, Lebar 35cm, T14cm',
                'finishing_type' => 'Translucent Hi-Glossy',
                'ready_stock' => 8,
                'safety_stock' => 5,
                'standard_cogs' => 450000.00,
                'selling_price' => 950000.00,
                'image_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'category_id' => 4,
                'product_code' => 'PRD-STP-003',
                'name' => 'Stepping Stone Batu Kali Slep Rata D35cm',
                'material_type' => 'batu_kali',
                'dimension_spec' => 'Diameter 30-38cm, Tebal 4cm',
                'finishing_type' => 'Slep Honed Doff',
                'ready_stock' => 45,
                'safety_stock' => 20,
                'standard_cogs' => 28000.00,
                'selling_price' => 65000.00,
                'image_path' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // 6. SEED CUSTOMERS
        DB::table('customers')->insert([
            [
                'id' => 1,
                'customer_code' => 'CUST-DPS-01',
                'name' => 'I Wayan Sugiarta',
                'company_name' => 'Bali Natural Living Gallery',
                'phone' => '081236778899',
                'email' => 'wayan@baliliving.com',
                'address' => 'Jl. Sunset Road No. 88, Seminyak',
                'city' => 'Denpasar, Bali',
                'customer_type' => 'distributor_ekspor',
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'customer_code' => 'CUST-SBY-02',
                'name' => 'Bambang Irawan',
                'company_name' => 'PT Citra Griya Asri',
                'phone' => '081122334455',
                'email' => 'bambang@citragriya.co.id',
                'address' => 'Jl. HR Muhammad No. 45',
                'city' => 'Surabaya',
                'customer_type' => 'kontraktor_arsitektur',
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // 7. SEED WORK ORDERS (SPK)
        DB::table('work_orders')->insert([
            [
                'id' => 1,
                'spk_number' => 'SPK/2026/04/001',
                'product_id' => 1,
                'customer_id' => 1,
                'target_quantity' => 14,
                'completed_quantity' => 12,
                'scrap_quantity' => 2,
                'status' => 'qc_phase',
                'priority' => 'high',
                'start_date' => Carbon::now()->subDays(2),
                'due_date' => Carbon::now()->addDays(2),
                'completion_date' => null,
                'notes' => 'Batch 14 wastafel putih, poles super glossy untuk export Bali',
                'created_by' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 2,
                'spk_number' => 'SPK/2026/04/002',
                'product_id' => 1,
                'customer_id' => 2,
                'target_quantity' => 14,
                'completed_quantity' => 0,
                'scrap_quantity' => 0,
                'status' => 'in_progress',
                'priority' => 'normal',
                'start_date' => Carbon::now()->subDay(),
                'due_date' => Carbon::now()->addDays(4),
                'completion_date' => null,
                'notes' => 'Pengerjaan Mesin Bubut 1-4 serentak',
                'created_by' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 3,
                'spk_number' => 'SPK/2026/04/004',
                'product_id' => 1,
                'customer_id' => null,
                'target_quantity' => 14,
                'completed_quantity' => 0,
                'scrap_quantity' => 0,
                'status' => 'in_progress',
                'priority' => 'normal',
                'start_date' => Carbon::now(),
                'due_date' => Carbon::now()->addDays(5),
                'completion_date' => null,
                'notes' => 'Tahap Pemotongan Mesin Slep (Pak Slamet)',
                'created_by' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 4,
                'spk_number' => 'SPK/2026/04/005',
                'product_id' => 2,
                'customer_id' => 1,
                'target_quantity' => 8,
                'completed_quantity' => 0,
                'scrap_quantity' => 0,
                'status' => 'scheduled',
                'priority' => 'urgent',
                'start_date' => Carbon::now()->addDay(),
                'due_date' => Carbon::now()->addDays(6),
                'completion_date' => null,
                'notes' => 'Pesanan khusus Onyx Oval, periksa serat tembus cahaya',
                'created_by' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
