#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register The Auto Loader
if (file_exists($maintenance = __DIR__.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

require __DIR__.'/vendor/autoload.php';

// Turn On The Lights, Illuminate The App
$app = require_once __DIR__.'/bootstrap/app.php';

// Run The Artisan Application
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
